fix(KatMovie4K): add missing suspend modifier to discoverEpisodes
The discoverEpisodes() function calls expandKmhdPacks() which is a
suspend function, but discoverEpisodes itself was missing the suspend
modifier. This caused a compilation error:

  e: KatMovie4KProvider.kt:429:28 Suspend function can only be called
     from a coroutine or another suspend function.

Also bumps version 7 -> 8.